import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { colors, fonts } from '../constants/theme';

export default function ConsentContent() {
  return (
    <ScrollView style={cs.scroll} showsVerticalScrollIndicator={true}>
      <Text style={cs.mainTitle}>Terms of Service, Privacy Policy & Legal Disclosures</Text>
      <Text style={cs.updated}>Last updated: February 2026</Text>

      <Text style={cs.intro}>
        By creating an account, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions, our Privacy Policy, and all applicable legal requirements outlined below.
      </Text>

      {/* AI DISCLAIMER */}
      <Text style={cs.heading}>AI-Generated Content Disclaimer</Text>
      <Text style={cs.body}>
        Veritas uses artificial intelligence (Claude AI) to analyze video content. All fact-check results are generated by AI, not by human fact-checkers. AI models are probabilistic and may produce inaccurate, incomplete, or erroneous outputs ("hallucinations"). You acknowledge that Veritas holds zero liability if the AI incorrectly labels a true statement as false, or vice versa. Users cannot sue for defamation, business damages, or any other losses based on the app's outputs.
      </Text>

      {/* GDPR */}
      <Text style={cs.heading}>GDPR Compliance (EU Users)</Text>
      <Text style={cs.body}>
        The General Data Protection Regulation (GDPR) applies to all users in the European Economic Area. If you submit a video containing people's faces or voices, our app processes personal data. We adhere to:
      </Text>
      <Text style={cs.bullet}>  Data Minimization — We only process what is strictly necessary for the fact-check. Video audio is extracted, transcribed, and analyzed. The original video file is immediately deleted after processing.</Text>
      <Text style={cs.bullet}>  Purpose Limitation — Your data is used exclusively for fact-checking analysis and is not repurposed for any other use, including advertising, profiling, or training.</Text>
      <Text style={cs.bullet}>  Right to be Forgotten — You may request complete deletion of all your data at any time through Account Settings. This permanently removes your account, scan history, and all associated data.</Text>

      {/* EU AI ACT */}
      <Text style={cs.heading}>EU AI Act Transparency (Effective August 2026)</Text>
      <Text style={cs.body}>
        Under the EU AI Act, Veritas is classified as a "Limited Risk" AI system. We are required to disclose that all fact-checking analysis is generated by artificial intelligence (Claude AI by Anthropic), not by human analysts or journalists. Our app does not perform banned AI practices including untargeted scraping of facial images, emotion recognition, social scoring, or biometric categorization.
      </Text>

      {/* COPYRIGHT & FAIR USE */}
      <Text style={cs.heading}>Copyright & Fair Use (US Law)</Text>
      <Text style={cs.body}>
        Users submit copyrighted videos (TikToks, YouTube Shorts, Instagram Reels) for analysis. Veritas operates under the Fair Use doctrine: our service is "transformative" — converting entertainment content into analytical fact-checking — and does not harm the market value of the original video. Our system strictly ingests the video, analyzes it, outputs the text analysis, and immediately deletes the video file. We do not host, store, redistribute, or republish original videos.
      </Text>

      {/* CCPA */}
      <Text style={cs.heading}>California Privacy (CCPA)</Text>
      <Text style={cs.body}>
        California residents have specific privacy rights under the California Consumer Privacy Act. We do not sell or share your personal data with third parties for advertising purposes. Data collected includes: email address, name, video URLs submitted for analysis, and transcription/analysis results. You may request disclosure or deletion of your data at any time.
      </Text>

      {/* THIRD-PARTY DISCLOSURES */}
      <Text style={cs.heading}>Third-Party Data Processing</Text>
      <Text style={cs.body}>
        Your data is transmitted to the following third-party sub-processors for analysis:
      </Text>
      <Text style={cs.bullet}>  Anthropic (API) — Text analysis and fact-checking (Claude AI). Data is processed according to Anthropic's data usage policies.</Text>
      <Text style={cs.bullet}>  Stripe — Payment processing for premium subscriptions. Stripe processes payment card data according to PCI DSS standards.</Text>
      <Text style={cs.bullet}>  Apple/Google — In-app purchases are processed through App Store/Google Play billing systems.</Text>
      <Text style={cs.body}>
        By using Veritas, you consent to this data being transmitted to and processed by these third-party services.
      </Text>

      {/* ACCEPTABLE USE */}
      <Text style={cs.heading}>Acceptable Use Policy</Text>
      <Text style={cs.body}>You agree NOT to use Veritas to:</Text>
      <Text style={cs.bullet}>  Generate harassment, defamation, or targeted abuse against any individual or group</Text>
      <Text style={cs.bullet}>  Create, distribute, or facilitate deepfakes or synthetic media</Text>
      <Text style={cs.bullet}>  Engage in illegal activity or attempt to verify content for illegal purposes</Text>
      <Text style={cs.bullet}>  Reverse-engineer, decompile, or attempt to extract the system prompts, AI models, or proprietary algorithms</Text>
      <Text style={cs.bullet}>  Mass-scrape the API or automate requests beyond reasonable personal use</Text>
      <Text style={cs.body}>
        Violation of this policy may result in immediate account suspension or termination.
      </Text>

      {/* IP OWNERSHIP */}
      <Text style={cs.heading}>Intellectual Property</Text>
      <Text style={cs.body}>
        You retain all rights to the video URLs and content you submit. The AI-generated analysis output is provided for your personal use. Veritas does not claim ownership of third-party social media videos submitted by users, nor of the AI-generated analysis results. The Veritas brand, interface, and technology are proprietary.
      </Text>

      {/* FUP */}
      <Text style={cs.heading}>Fair Use Policy (FUP) for Premium</Text>
      <Text style={cs.body}>
        Premium subscriptions are marketed as "Unlimited" but are subject to a Fair Use Policy. We reserve the right to unilaterally throttle, suspend, or ban accounts that demonstrate abusive usage patterns, including but not limited to: automated/scripted requests, mass API scraping, or usage exceeding reasonable personal consumption levels.
      </Text>

      {/* LIABILITY */}
      <Text style={cs.heading}>Limitation of Liability</Text>
      <Text style={cs.body}>
        VERITAS IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. IN NO EVENT SHALL VERITAS, ITS CREATORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO REPUTATIONAL HARM, LOST PROFITS, OR RELIANCE ON AI-GENERATED CONTENT. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE SERVICE IN THE PRECEDING 12 MONTHS.
      </Text>

      <View style={cs.spacer} />
    </ScrollView>
  );
}

const cs = StyleSheet.create({
  scroll: { flex: 1, paddingHorizontal: 4 },
  mainTitle: { fontSize: 18, fontFamily: fonts.semiBold, color: colors.text, marginBottom: 4 },
  updated: { fontSize: 12, fontFamily: fonts.regular, color: colors.textMuted, marginBottom: 20 },
  intro: { fontSize: 14, fontFamily: fonts.regular, color: colors.textSecondary, lineHeight: 22, marginBottom: 20 },
  heading: { fontSize: 16, fontFamily: fonts.semiBold, color: colors.accent, marginTop: 20, marginBottom: 10 },
  body: { fontSize: 14, fontFamily: fonts.regular, color: colors.textSecondary, lineHeight: 22, marginBottom: 8 },
  bullet: { fontSize: 14, fontFamily: fonts.regular, color: colors.textSecondary, lineHeight: 22, marginBottom: 6, paddingLeft: 8 },
  spacer: { height: 32 },
});
