import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet,
  ScrollView, Modal,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import ConsentContent from '../components/ConsentContent';
import { colors, fonts, radius, spacing } from '../constants/theme';

export const WELCOME_ACCEPTED_KEY = '@veritas_welcome_accepted';

/**
 * First-launch welcome + disclaimer screen.
 *
 * Shown once, before the login/signup flow, so every user sees the key caveats
 * up front rather than buried behind a checkbox. Acceptance is persisted in
 * AsyncStorage so returning users go straight to login.
 */
export default function WelcomeScreen() {
  const [showLegal, setShowLegal] = useState(false);
  const router = useRouter();

  async function handleAccept() {
    try {
      await AsyncStorage.setItem(WELCOME_ACCEPTED_KEY, 'true');
    } catch {
      // Non-fatal — if storage is unavailable, they'll just see the screen
      // again next launch. Don't block the flow.
    }
    router.replace('/');
  }

  return (
    <SafeAreaView style={s.safe}>
      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
        <View style={s.header}>
          <Ionicons name="sparkles" size={20} color={colors.accent} />
          <Text style={s.brand}>VERITAS</Text>
        </View>

        <Text style={s.title}>Before we start</Text>
        <Text style={s.subtitle}>
          Veritas is a research preview. Here's what that means, in plain language.
        </Text>

        <View style={s.card}>
          <View style={s.row}>
            <Ionicons name="flask" size={22} color={colors.accent} style={s.icon} />
            <View style={s.rowText}>
              <Text style={s.rowTitle}>It's AI, not a human fact-checker</Text>
              <Text style={s.rowBody}>
                Every verdict is generated by a language model. It can be wrong,
                miss context, or hallucinate. Don't treat results as final truth.
              </Text>
            </View>
          </View>

          <View style={s.divider} />

          <View style={s.row}>
            <Ionicons name="search" size={22} color={colors.accent} style={s.icon} />
            <View style={s.rowText}>
              <Text style={s.rowTitle}>Use it as a starting point</Text>
              <Text style={s.rowBody}>
                Read the sources Veritas cites. Check them yourself for anything
                that matters. The app gives you a head start, not an answer.
              </Text>
            </View>
          </View>

          <View style={s.divider} />

          <View style={s.row}>
            <Ionicons name="lock-closed" size={22} color={colors.accent} style={s.icon} />
            <View style={s.rowText}>
              <Text style={s.rowTitle}>Your data</Text>
              <Text style={s.rowBody}>
                Videos are downloaded, analyzed, and deleted. We store your
                email, account, and scan history. You can delete everything
                from Settings at any time.
              </Text>
            </View>
          </View>
        </View>

        <TouchableOpacity onPress={() => setShowLegal(true)} style={s.legalLinkBtn}>
          <Text style={s.legalLinkText}>Read the full terms, privacy, and legal disclosures</Text>
          <Ionicons name="chevron-forward" size={16} color={colors.accent} />
        </TouchableOpacity>

        <TouchableOpacity
          testID="welcome-continue-btn"
          style={s.continueBtn}
          onPress={handleAccept}
        >
          <Text style={s.continueText}>I understand, continue</Text>
        </TouchableOpacity>

        <Text style={s.footer}>
          Tapping continue means you've read this and accept the terms linked above.
        </Text>
      </ScrollView>

      {/* Full legal modal — reuses the shared ConsentContent component. */}
      <Modal
        visible={showLegal}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setShowLegal(false)}
      >
        <SafeAreaView style={s.modalSafe}>
          <View style={s.modalHeader}>
            <Text style={s.modalTitle}>Legal</Text>
            <TouchableOpacity testID="close-legal-modal" onPress={() => setShowLegal(false)}>
              <Ionicons name="close" size={24} color={colors.text} />
            </TouchableOpacity>
          </View>
          <ConsentContent />
        </SafeAreaView>
      </Modal>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  scroll: { padding: spacing.lg, paddingBottom: spacing.xxl },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: spacing.md, marginBottom: spacing.xl,
  },
  brand: {
    fontFamily: fonts.semiBold, fontSize: 12, color: colors.textSecondary,
    letterSpacing: 4,
  },
  title: {
    fontFamily: fonts.semiBold, fontSize: 32, color: colors.text,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontFamily: fonts.regular, fontSize: 16, color: colors.textSecondary,
    lineHeight: 24, marginBottom: spacing.xl,
  },
  card: {
    backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border,
    borderRadius: radius.lg, padding: spacing.lg,
  },
  row: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  icon: { marginTop: 2 },
  rowText: { flex: 1 },
  rowTitle: {
    fontFamily: fonts.semiBold, fontSize: 15, color: colors.text,
    marginBottom: 4,
  },
  rowBody: {
    fontFamily: fonts.regular, fontSize: 14, color: colors.textSecondary,
    lineHeight: 20,
  },
  divider: {
    height: 1, backgroundColor: colors.border, marginVertical: spacing.md,
  },
  legalLinkBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 4, paddingVertical: spacing.md, marginTop: spacing.md,
  },
  legalLinkText: {
    fontFamily: fonts.semiBold, fontSize: 14, color: colors.accent,
  },
  continueBtn: {
    backgroundColor: colors.accent, borderRadius: radius.lg,
    paddingVertical: 16, alignItems: 'center', marginTop: spacing.md,
  },
  continueText: {
    fontFamily: fonts.semiBold, fontSize: 16, color: colors.bg,
  },
  footer: {
    fontFamily: fonts.regular, fontSize: 12, color: colors.textMuted,
    textAlign: 'center', marginTop: spacing.md, lineHeight: 18,
  },
  modalSafe: { flex: 1, backgroundColor: colors.bg },
  modalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: spacing.lg, paddingVertical: spacing.md,
    borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  modalTitle: {
    fontFamily: fonts.semiBold, fontSize: 18, color: colors.text,
  },
});
